name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v
     - name: Run Feed Generator
       uses: juchambo/podcast-generator@main
